<a href="https://colab.research.google.com/github/nsthomp5/MAT422/blob/main/MAT_422_HW_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Name: Nicholas Thompson
# ID: 1223100502
# Class: MAT 422
# Assignment: HW 1.4

In [26]:
import numpy as np
import math
from numpy import linalg
from numpy import random

Singular Value Decomposition (SVD) factors a matrix into three others using eigenvalues and eigenvectors. Applications range from various matrix operations to making image-based representations of data easier to work with. Each of the U, S, and V matrices organizes useful information to be used for various purposes, and a goal of machine learning is to use as easy-to-handle data as possible.

In [13]:
# 1.4.1 SVD
# Example 1: SVD function

A = np.array([[3,4,5,6],[1,4,9,8],[4,5,3,4]]) # Example 3x4 matrix A
U, S, V = np.linalg.svd(A) # using SVD function #S can be derived from U or W, diagonal matrix of eigenvalues
S = np.diag(S)
print("Matrix U is " + str(U))
print("Matrix S is " + str(S))
print("Matrix V is " + str(V))



Matrix U is [[ 0.5370015   0.21028875 -0.81695044]
 [ 0.72527578 -0.60967024  0.31980813]
 [ 0.43081832  0.76425182  0.47991117]]
Matrix S is [[17.15308852  0.          0.        ]
 [ 0.          4.39592041  0.        ]
 [ 0.          0.          0.66890802]]
Matrix V is [[ 0.23666604  0.41993608  0.61242292  0.62656288]
 [ 0.7002409   0.50586291 -0.48745946 -0.12707741]
 [-0.31603525  0.61441422  0.3487093  -0.63326039]
 [-0.59478869  0.43617837 -0.51548353  0.43617837]]


In [5]:
# Example 2: SVD process breakdown

A_t=np.transpose(A) #going through SVD process manually
W = A @ A_t


U = np.linalg.eig(W)[1] #U matrix comprised of eigenvectors of W
print(U)

Y = A_t @ A #Obtaining V is reverse of obtaining U


V = np.linalg.eig(Y)[1]
print(V)

S = np.diag(np.sqrt(np.linalg.eig(W)[0])) #S can be derived from U or W, diagonal matrix of eigenvalues
print(S)

[[ 0.5370015   0.81695044  0.21028875]
 [ 0.72527578 -0.31980813 -0.60967024]
 [ 0.43081832 -0.47991117  0.76425182]]
[[ 0.23666604  0.7002409   0.59478869  0.31603525]
 [ 0.41993608  0.50586291 -0.43617837 -0.61441422]
 [ 0.61242292 -0.48745946  0.51548353 -0.3487093 ]
 [ 0.62656288 -0.12707741 -0.43617837  0.63326039]]
[[17.15308852  0.          0.        ]
 [ 0.          0.66890802  0.        ]
 [ 0.          0.          4.39592041]]


Low-rank matrix approximation is like other linear algebra techniques relevant to machine learning, as it reduces the dimensions of a matrix to be less computationally costly when used for machine learning purposes. In this case, low-rank approximations decrease the number of features necessary for a model by reducing a matrix to an approximation of itself with a lower rank, making it less computationally costly to pull data from. This is done using SVD, adding another application to a long list of them.

In [6]:
# 1.4.2 Low-rank matrix approximations
# Example 1: Using SVD

A = np.array([[3,4,5,6],[1,4,9,8],[4,5,3,4]]) # Example 3x4 matrix A
U, S, V = np.linalg.svd(A) # using SVD function
print("Matrix U is " + str(U))
print("Matrix S is " + str(S))
print("Matrix V is " + str(V))
print(S)
print(V)



Matrix U is [[ 0.5370015   0.21028875 -0.81695044]
 [ 0.72527578 -0.60967024  0.31980813]
 [ 0.43081832  0.76425182  0.47991117]]
Matrix S is [17.15308852  4.39592041  0.66890802]
Matrix V is [[ 0.23666604  0.41993608  0.61242292  0.62656288]
 [ 0.7002409   0.50586291 -0.48745946 -0.12707741]
 [-0.31603525  0.61441422  0.3487093  -0.63326039]
 [-0.59478869  0.43617837 -0.51548353  0.43617837]]
[17.15308852  4.39592041  0.66890802]
[[ 0.23666604  0.41993608  0.61242292  0.62656288]
 [ 0.7002409   0.50586291 -0.48745946 -0.12707741]
 [-0.31603525  0.61441422  0.3487093  -0.63326039]
 [-0.59478869  0.43617837 -0.51548353  0.43617837]]


In [23]:
r = 1 # rank
U = U[:, :S.shape[0]] # matching dimensions of U with S
S = np.diag(S) # S as a diagonal matrix of eigenvalues


R = U[:, :r] @ S[:r, :r] @ V[:r, :] #pinching U, S, V to the lowest rank of the three and multiplying
print(R) # low-rank approximation

[[2.17998638 3.86812963 5.64117099 5.77141751]
 [2.94429589 5.22430705 7.61898183 7.79489315]
 [1.74893007 3.10327087 4.52572259 4.63021501]]


Principal Component Analysis is used to reduce the dimensions of data by choosing a subset of features to analyze. The features with the most variability are chosen first, as they represent the largest differences between the individual data points, so they are chosen as principal features first because they are more likely to be predictive of outputs. Eigenvalues and eigenvectors are used again, as they can be applied to many areas of machine learning, as well as other math and data science applications like differential equations and data structures.

In [67]:
# 1.4.3 Principal Component Analysis
# Example 1: Baseball Stats

x = np.zeros([40,5]) #dataset generation

x[:,0] = np.random.randint(60,100,40)/300 # batting average
x[:,1] = np.random.randint(300,400,40)/10 # hard-hit %
x[:,2] = np.random.randint(0,25,40) # SEAGER
x[:,3] = np.random.randint(50,350,40)/100 # ISO
x[:,4] = np.random.randint(5,20,40) # pulled flyball %

x_centered = np.zeros([40,5])

for i in range(5):
    x_centered[:,i] = x[:,i] - np.mean(x[:,i]) # centering the data around the mean


cov_matrix = np.cov(x_centered, rowvar = False) #covariance matrix

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix) # eigenvalues and eigenvectors of covariance matrix



Then, since each eigenvalue represents the variability of a principal component, sorting the eigenvalues will sort the principal components by their variability.

In [68]:
sorted_comp = np.argsort(eigenvalues)[::-1] # sorts eigenvalues for component variability

sorted_eigenvalues = eigenvalues[sorted_comp] # new array

sorted_eigenvectors = eigenvectors[sorted_comp] # new array of eigenvectors by eigenvalue sort



In [71]:
comp_num = 1 # choose number of components

In [72]:
comp_subset = sorted_eigenvectors[:,0:comp_num] # reduces eigenvector array to chosen number of components to analyze

x_reduced = np.dot(comp_subset.transpose(),x_centered.transpose()).transpose() # dot product scales data based on principal components outputs lower-dimensional data

print(x_reduced)

[[ -8.00180045]
 [-10.93506398]
 [  6.04996419]
 [ -0.20839737]
 [ -3.58296331]
 [  6.12628514]
 [ -8.74690002]
 [ -0.11915512]
 [  1.86774561]
 [ -2.76024026]
 [  8.7920319 ]
 [-11.76365844]
 [ -5.11653793]
 [  3.87049983]
 [ -0.2493645 ]
 [  8.26554559]
 [  6.97983602]
 [  1.11525187]
 [  0.79391242]
 [ 10.3139042 ]
 [ 10.07163027]
 [ 11.12593081]
 [ -4.84187254]
 [ -9.06744157]
 [  6.27157946]
 [ 11.81321405]
 [  2.01136671]
 [  4.03173355]
 [-12.14924791]
 [  5.39759902]
 [ -7.07381111]
 [ -3.9477822 ]
 [  7.80649459]
 [ -8.660521  ]
 [-10.15467857]
 [ 12.28625143]
 [ -7.97126375]
 [ -3.97442525]
 [ -5.95839941]
 [  0.29274802]]


The resulting output shows the data rescaled to weight the most high-variance parameters, so it can be presented and programmed in a more organized fashion while still representing the impacts of all features.