<a href="https://colab.research.google.com/github/nsthomp5/MAT422/blob/main/MAT_422_HW_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
# Name: Nicholas Thompson
# ID: 1223100502
# Class: MAT 422
# Assignment: HW 1.3

In [56]:
import numpy as np
import math
from numpy import linalg

QR Decomposition factorizes a matrix into two using norms and projections, forming each matrix as an array of vectors. The following program improves upon my HW 1.2 by taking input entries of vectors of any amount and uniform size. My Gram-Schmidt process returns an error, however.

In [82]:
#1.3.1 QR Decomposition
#Example 1

def proj_vec(u,v): # function for producing projection of one vector onto another
  for i in range(len(u)):
    u[i] = (np.dot(u,v)/np.dot(u,u))*u[i]
  return u

def gram_schmidt(u): # function for gram-schmidt process
  count = 1
  for i in range(len(u[0])):
    for j in range (count):
      if j == 0:
        u[:,i] = u[:,i]
      else:
        u[:,i] = u[:,i] - proj_vec(u[:,j],u[:,i])
    count+=1
  return u

In [84]:
vec_dim = int(input("Choose a column vector size: ")) # user inputs
vec_num = int(input("Choose a number of vectors to enter: "))
A = np.zeros((vec_dim, vec_num)) # forms array of vectors as a matrix

for i in range(vec_num):
  for j in range (vec_dim):
    A[j,i] = float(input("Enter an element of vector number " + str(i+1) + ": ")) # user-input matrix entries

Q = gram_schmidt(A)
for i in range (vec_num): # rescaling Q to unit vectors (I get errors here too)
  for j in range (vec_dim):
    Q[j,i] = Q[j,i]/np.linalg.norm(Q[:,i])

R = np.zeros((len(Q[0]),len(Q[0]))) # upper triangular matrix R
for i in range(len(Q[0])):
  for j in range(i,len(Q[0])):
    if i >= j:
      R[i,j] = np.dot(Q[:,i],A[:,j])
    else:
      R[i,j] = 0

print("Q = \n", Q)
print("R = \n", R)

Choose a column vector size: 2
Choose a number of vectors to enter: 3
Enter an element of vector number 1: 2
Enter an element of vector number 1: 4
Enter an element of vector number 2: 3
Enter an element of vector number 2: 5
Enter an element of vector number 3: 1
Enter an element of vector number 3: 6
Q = 
 [[0.4472136         nan        nan]
 [0.99380799        nan        nan]]
R = 
 [[1.18765432 0.         0.        ]
 [0.                nan 0.        ]
 [0.         0.                nan]]


<ipython-input-82-ca68c564b9d6>:6: RuntimeWarning: invalid value encountered in scalar divide
  u[i] = (np.dot(u,v)/np.dot(u,u))*u[i]


Least-squares problems have to do with approximating solutions by minimizing the sum of squares. In the context of linear algebra, this is done by minimizing the sum of the squared entries of b-Ax, done by manipulating the vector x, where A is a matrix and b is a vector.

In [99]:
#1.3.2 Least Squares
#Example 1

A = [[1,2,3],[3,5,7],[2,4,5]]
b = [[3],[5],[3]]

np.linalg.lstsq(A,b,rcond=None) # Returns x for Ax=b

(array([[-2.],
        [-2.],
        [ 3.]]),
 array([], dtype=float64),
 3,
 array([11.90897874,  0.3388389 ,  0.24781764]))

In [98]:
#Example 2

A = [[3,1,4,2],[5,2,3,9],[10,1,5,11],[30,2,8,12]]
b = [[3],[5],[3],[4]]

np.linalg.lstsq(A,b,rcond=None) # Returns x for Ax=b

(array([[-0.09913793],
        [ 2.13362069],
        [ 0.26724138],
        [ 0.04741379]]),
 array([], dtype=float64),
 4,
 array([37.76587205,  8.51855608,  2.85525177,  1.01027141]))

Linear regression uses least-squares methods as well. Linear regression involves finding the optimal coefficients for a linear function to find the line of best fit for a linear relationship between known inputs and outputs. It does this by minimizing the sum of squares of the differences between the output predicted by the line of best fit and the actual output.

In [110]:
#1.3.3 Linear Regression
#Example 1: Dot Product

from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


X = np.array([[1,2,3],[2,1,1],[1,4,6],[2,4,1]])
y = np.dot(X,np.array([1,5,2])) # 1, 5, 2 are feature coefficients

print(reg.score(X,y)) # R^2

reg = LinearRegression().fit(X,y) # Optimizes coefficients

reg.predict([[1,2,5]]) # Uses optimized coefficients to produce output



0.9128697042366105


array([21.])

In [111]:
#Example 2: Worse Fit

y = [18,7,29,21.5] # Outputs slightly off from dot product

print(reg.score(X,y))

reg = LinearRegression().fit(X,y)

reg.predict([[1,2,5]])

0.8915153023140086


array([18.88888889])

In [112]:
#Example 3: Terrible Fit

y = [50,100,0,3] # Outputs not even close dot

print(reg.score(X,y))

reg = LinearRegression().fit(X,y)

reg.predict([[1,2,5]])

-0.6308634093213654


array([59.77777778])